-- =====================================================
-- TÜRKİYE ARAÇ VERİTABANI
-- MR HASAR DANIŞMANLIK
-- 85+ Marka, 1500+ Model/Paket
-- =====================================================

DROP TABLE IF EXISTS arac_veritabani;

CREATE TABLE arac_veritabani (
    id INT AUTO_INCREMENT PRIMARY KEY,
    marka VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    paket VARCHAR(100) NULL,
    yil_baslangic INT DEFAULT 2000,
    yil_bitis INT DEFAULT 2025,
    segment ENUM('A','B','C','D','E','F','SUV','MPV','PICKUP','TİCARİ') DEFAULT 'C',
    yakit_tipi ENUM('BENZİN','DİZEL','HİBRİT','ELEKTRİK','LPG') DEFAULT 'BENZİN',
    aktif TINYINT(1) DEFAULT 1,
    INDEX idx_marka (marka),
    INDEX idx_model (model),
    INDEX idx_marka_model (marka, model)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_turkish_ci;

-- =====================================================
-- MARKALAR VE MODELLER
-- =====================================================

-- ALFA ROMEO
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('ALFA ROMEO', 'GIULIA', '2.0 TB SUPER', 'D'),
('ALFA ROMEO', 'GIULIA', '2.0 TB VELOCE', 'D'),
('ALFA ROMEO', 'GIULIA', '2.9 V6 QUADRIFOGLIO', 'D'),
('ALFA ROMEO', 'STELVIO', '2.0 TB SUPER', 'SUV'),
('ALFA ROMEO', 'STELVIO', '2.0 TB VELOCE', 'SUV'),
('ALFA ROMEO', 'STELVIO', '2.9 V6 QUADRIFOGLIO', 'SUV'),
('ALFA ROMEO', 'TONALE', '1.5 T HYBRID SUPER', 'SUV'),
('ALFA ROMEO', 'TONALE', '1.5 T HYBRID VELOCE', 'SUV');

-- ASTON MARTIN
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('ASTON MARTIN', 'DB11', 'V8 COUPE', 'F'),
('ASTON MARTIN', 'DB11', 'V12 COUPE', 'F'),
('ASTON MARTIN', 'VANTAGE', 'V8 COUPE', 'F'),
('ASTON MARTIN', 'DBX', 'V8', 'SUV'),
('ASTON MARTIN', 'DBX', '707', 'SUV');

-- AUDI
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('AUDI', 'A1', '1.0 TFSI SPORTBACK', 'B'),
('AUDI', 'A1', '1.5 TFSI S-LINE', 'B'),
('AUDI', 'A3', '1.0 TFSI SPORTBACK', 'C'),
('AUDI', 'A3', '1.5 TFSI SPORTBACK', 'C'),
('AUDI', 'A3', '2.0 TDI SPORTBACK', 'C'),
('AUDI', 'A3', '35 TFSI S-LINE', 'C'),
('AUDI', 'A3', 'S3 SPORTBACK', 'C'),
('AUDI', 'A3', 'RS3 SPORTBACK', 'C'),
('AUDI', 'A4', '2.0 TFSI SEDAN', 'D'),
('AUDI', 'A4', '2.0 TDI SEDAN', 'D'),
('AUDI', 'A4', '40 TFSI S-LINE', 'D'),
('AUDI', 'A4', '45 TFSI QUATTRO', 'D'),
('AUDI', 'A4', 'S4 SEDAN', 'D'),
('AUDI', 'A4', 'RS4 AVANT', 'D'),
('AUDI', 'A5', '2.0 TFSI COUPE', 'D'),
('AUDI', 'A5', '2.0 TFSI SPORTBACK', 'D'),
('AUDI', 'A5', '40 TDI QUATTRO', 'D'),
('AUDI', 'A5', 'S5 SPORTBACK', 'D'),
('AUDI', 'A5', 'RS5 COUPE', 'D'),
('AUDI', 'A6', '2.0 TFSI SEDAN', 'E'),
('AUDI', 'A6', '2.0 TDI SEDAN', 'E'),
('AUDI', 'A6', '45 TFSI QUATTRO', 'E'),
('AUDI', 'A6', '55 TFSI QUATTRO', 'E'),
('AUDI', 'A6', 'S6 SEDAN', 'E'),
('AUDI', 'A6', 'RS6 AVANT', 'E'),
('AUDI', 'A7', '55 TFSI QUATTRO', 'E'),
('AUDI', 'A7', 'S7 SPORTBACK', 'E'),
('AUDI', 'A7', 'RS7 SPORTBACK', 'E'),
('AUDI', 'A8', '55 TFSI QUATTRO', 'F'),
('AUDI', 'A8', '60 TFSI QUATTRO', 'F'),
('AUDI', 'A8', 'S8', 'F'),
('AUDI', 'Q2', '1.0 TFSI', 'SUV'),
('AUDI', 'Q2', '1.5 TFSI S-LINE', 'SUV'),
('AUDI', 'Q3', '1.5 TFSI', 'SUV'),
('AUDI', 'Q3', '2.0 TDI QUATTRO', 'SUV'),
('AUDI', 'Q3', '35 TFSI S-LINE', 'SUV'),
('AUDI', 'Q3', 'RS Q3', 'SUV'),
('AUDI', 'Q5', '2.0 TFSI QUATTRO', 'SUV'),
('AUDI', 'Q5', '2.0 TDI QUATTRO', 'SUV'),
('AUDI', 'Q5', '45 TFSI S-LINE', 'SUV'),
('AUDI', 'Q5', 'SQ5', 'SUV'),
('AUDI', 'Q7', '3.0 TDI QUATTRO', 'SUV'),
('AUDI', 'Q7', '55 TFSI QUATTRO', 'SUV'),
('AUDI', 'Q7', 'SQ7', 'SUV'),
('AUDI', 'Q8', '55 TFSI QUATTRO', 'SUV'),
('AUDI', 'Q8', 'SQ8', 'SUV'),
('AUDI', 'Q8', 'RS Q8', 'SUV'),
('AUDI', 'E-TRON', '55 QUATTRO', 'SUV'),
('AUDI', 'E-TRON GT', 'QUATTRO', 'E'),
('AUDI', 'E-TRON GT', 'RS', 'E'),
('AUDI', 'TT', '2.0 TFSI COUPE', 'C'),
('AUDI', 'TT', 'TTS COUPE', 'C'),
('AUDI', 'TT', 'RS COUPE', 'C'),
('AUDI', 'R8', 'V10 COUPE', 'F'),
('AUDI', 'R8', 'V10 PERFORMANCE', 'F');

-- BENTLEY
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('BENTLEY', 'CONTINENTAL GT', 'V8', 'F'),
('BENTLEY', 'CONTINENTAL GT', 'W12', 'F'),
('BENTLEY', 'FLYING SPUR', 'V8', 'F'),
('BENTLEY', 'FLYING SPUR', 'W12', 'F'),
('BENTLEY', 'BENTAYGA', 'V8', 'SUV'),
('BENTLEY', 'BENTAYGA', 'W12 SPEED', 'SUV');

-- BMW
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('BMW', '1 SERİSİ', '116i JOY', 'C'),
('BMW', '1 SERİSİ', '118i M SPORT', 'C'),
('BMW', '1 SERİSİ', '120i M SPORT', 'C'),
('BMW', '1 SERİSİ', 'M135i xDRIVE', 'C'),
('BMW', '2 SERİSİ COUPE', '220i', 'C'),
('BMW', '2 SERİSİ COUPE', 'M240i xDRIVE', 'C'),
('BMW', '2 SERİSİ GRAN COUPE', '218i', 'C'),
('BMW', '2 SERİSİ GRAN COUPE', '220i M SPORT', 'C'),
('BMW', '2 SERİSİ ACTIVE TOURER', '218i', 'MPV'),
('BMW', '2 SERİSİ ACTIVE TOURER', '220i', 'MPV'),
('BMW', '3 SERİSİ', '318i', 'D'),
('BMW', '3 SERİSİ', '320i', 'D'),
('BMW', '3 SERİSİ', '320i M SPORT', 'D'),
('BMW', '3 SERİSİ', '320d', 'D'),
('BMW', '3 SERİSİ', '330i', 'D'),
('BMW', '3 SERİSİ', '330i M SPORT', 'D'),
('BMW', '3 SERİSİ', '330e HYBRID', 'D'),
('BMW', '3 SERİSİ', 'M340i xDRIVE', 'D'),
('BMW', '3 SERİSİ', 'M3 COMPETITION', 'D'),
('BMW', '4 SERİSİ COUPE', '420i', 'D'),
('BMW', '4 SERİSİ COUPE', '430i M SPORT', 'D'),
('BMW', '4 SERİSİ COUPE', 'M440i xDRIVE', 'D'),
('BMW', '4 SERİSİ COUPE', 'M4 COMPETITION', 'D'),
('BMW', '4 SERİSİ GRAN COUPE', '420i', 'D'),
('BMW', '4 SERİSİ GRAN COUPE', '430i M SPORT', 'D'),
('BMW', '4 SERİSİ CABRIO', '420i', 'D'),
('BMW', '4 SERİSİ CABRIO', 'M440i xDRIVE', 'D'),
('BMW', '5 SERİSİ', '520i', 'E'),
('BMW', '5 SERİSİ', '520i M SPORT', 'E'),
('BMW', '5 SERİSİ', '520d', 'E'),
('BMW', '5 SERİSİ', '530i', 'E'),
('BMW', '5 SERİSİ', '530i M SPORT', 'E'),
('BMW', '5 SERİSİ', '530e HYBRID', 'E'),
('BMW', '5 SERİSİ', '540i xDRIVE', 'E'),
('BMW', '5 SERİSİ', 'M550i xDRIVE', 'E'),
('BMW', '5 SERİSİ', 'M5 COMPETITION', 'E'),
('BMW', '6 SERİSİ GT', '630i', 'E'),
('BMW', '6 SERİSİ GT', '640i xDRIVE', 'E'),
('BMW', '7 SERİSİ', '735i', 'F'),
('BMW', '7 SERİSİ', '740i', 'F'),
('BMW', '7 SERİSİ', '740d xDRIVE', 'F'),
('BMW', '7 SERİSİ', '750i xDRIVE', 'F'),
('BMW', '7 SERİSİ', 'M760i xDRIVE', 'F'),
('BMW', '8 SERİSİ COUPE', '840i', 'F'),
('BMW', '8 SERİSİ COUPE', 'M850i xDRIVE', 'F'),
('BMW', '8 SERİSİ GRAN COUPE', '840i', 'F'),
('BMW', '8 SERİSİ GRAN COUPE', 'M850i xDRIVE', 'F'),
('BMW', 'M8', 'COMPETITION COUPE', 'F'),
('BMW', 'M8', 'COMPETITION GRAN COUPE', 'F'),
('BMW', 'X1', 'sDRIVE18i', 'SUV'),
('BMW', 'X1', 'sDRIVE20i', 'SUV'),
('BMW', 'X1', 'xDRIVE20i M SPORT', 'SUV'),
('BMW', 'X1', 'xDRIVE25e HYBRID', 'SUV'),
('BMW', 'X2', 'sDRIVE18i', 'SUV'),
('BMW', 'X2', 'xDRIVE20i M SPORT', 'SUV'),
('BMW', 'X3', 'sDRIVE20i', 'SUV'),
('BMW', 'X3', 'xDRIVE20i', 'SUV'),
('BMW', 'X3', 'xDRIVE30i M SPORT', 'SUV'),
('BMW', 'X3', 'xDRIVE30e HYBRID', 'SUV'),
('BMW', 'X3', 'M40i', 'SUV'),
('BMW', 'X3 M', 'COMPETITION', 'SUV'),
('BMW', 'X4', 'xDRIVE20i', 'SUV'),
('BMW', 'X4', 'xDRIVE30i M SPORT', 'SUV'),
('BMW', 'X4', 'M40i', 'SUV'),
('BMW', 'X4 M', 'COMPETITION', 'SUV'),
('BMW', 'X5', 'xDRIVE40i', 'SUV'),
('BMW', 'X5', 'xDRIVE45e HYBRID', 'SUV'),
('BMW', 'X5', 'M50i', 'SUV'),
('BMW', 'X5 M', 'COMPETITION', 'SUV'),
('BMW', 'X6', 'xDRIVE40i', 'SUV'),
('BMW', 'X6', 'M50i', 'SUV'),
('BMW', 'X6 M', 'COMPETITION', 'SUV'),
('BMW', 'X7', 'xDRIVE40i', 'SUV'),
('BMW', 'X7', 'xDRIVE40d', 'SUV'),
('BMW', 'X7', 'M50i', 'SUV'),
('BMW', 'XM', 'LABEL RED', 'SUV'),
('BMW', 'iX', 'xDRIVE40', 'SUV'),
('BMW', 'iX', 'xDRIVE50', 'SUV'),
('BMW', 'iX', 'M60', 'SUV'),
('BMW', 'iX1', 'xDRIVE30', 'SUV'),
('BMW', 'iX3', 'eDRIVE', 'SUV'),
('BMW', 'i4', 'eDRIVE40', 'D'),
('BMW', 'i4', 'M50', 'D'),
('BMW', 'i5', 'eDRIVE40', 'E'),
('BMW', 'i5', 'M60 xDRIVE', 'E'),
('BMW', 'i7', 'xDRIVE60', 'F'),
('BMW', 'i7', 'M70 xDRIVE', 'F'),
('BMW', 'Z4', 'sDRIVE20i', 'C'),
('BMW', 'Z4', 'M40i', 'C');

-- CHERY
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('CHERY', 'TIGGO 4 PRO', '1.5 CVT COMFORT', 'SUV'),
('CHERY', 'TIGGO 4 PRO', '1.5 CVT LUXURY', 'SUV'),
('CHERY', 'TIGGO 7 PRO', '1.5T CVT COMFORT', 'SUV'),
('CHERY', 'TIGGO 7 PRO', '1.5T CVT LUXURY', 'SUV'),
('CHERY', 'TIGGO 8 PRO', '1.6T DCT LUXURY', 'SUV'),
('CHERY', 'TIGGO 8 PRO', '1.6T DCT PREMIUM', 'SUV'),
('CHERY', 'ARRIZO 6', '1.5T CVT COMFORT', 'C'),
('CHERY', 'ARRIZO 6', '1.5T CVT LUXURY', 'C');

-- CHEVROLET
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('CHEVROLET', 'AVEO', '1.2 LS', 'B'),
('CHEVROLET', 'AVEO', '1.4 LT', 'B'),
('CHEVROLET', 'CRUZE', '1.4 T LS', 'C'),
('CHEVROLET', 'CRUZE', '1.6 LT', 'C'),
('CHEVROLET', 'SPARK', '1.0 LS', 'A'),
('CHEVROLET', 'SPARK', '1.2 LT', 'A'),
('CHEVROLET', 'TRAX', '1.4 T LT', 'SUV'),
('CHEVROLET', 'TRAX', '1.4 T LTZ', 'SUV'),
('CHEVROLET', 'CAPTIVA', '1.5 T LS', 'SUV'),
('CHEVROLET', 'CAPTIVA', '1.5 T LT', 'SUV');

-- CITROEN
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('CITROEN', 'C1', '1.0 VTi FEEL', 'A'),
('CITROEN', 'C1', '1.0 VTi SHINE', 'A'),
('CITROEN', 'C3', '1.2 PURETECH FEEL', 'B'),
('CITROEN', 'C3', '1.2 PURETECH SHINE', 'B'),
('CITROEN', 'C3', '1.5 BLUEHDI SHINE', 'B'),
('CITROEN', 'C3 AIRCROSS', '1.2 PURETECH FEEL', 'SUV'),
('CITROEN', 'C3 AIRCROSS', '1.2 PURETECH SHINE', 'SUV'),
('CITROEN', 'C3 AIRCROSS', '1.5 BLUEHDI SHINE', 'SUV'),
('CITROEN', 'C4', '1.2 PURETECH FEEL', 'C'),
('CITROEN', 'C4', '1.2 PURETECH SHINE', 'C'),
('CITROEN', 'C4', '1.5 BLUEHDI SHINE', 'C'),
('CITROEN', 'C4 X', '1.2 PURETECH FEEL', 'C'),
('CITROEN', 'C4 X', '1.2 PURETECH SHINE', 'C'),
('CITROEN', 'C5 AIRCROSS', '1.2 PURETECH FEEL', 'SUV'),
('CITROEN', 'C5 AIRCROSS', '1.5 BLUEHDI FEEL', 'SUV'),
('CITROEN', 'C5 AIRCROSS', '1.6 PURETECH SHINE', 'SUV'),
('CITROEN', 'C5 X', '1.2 PURETECH FEEL', 'D'),
('CITROEN', 'C5 X', '1.6 PURETECH SHINE', 'D'),
('CITROEN', 'BERLINGO', '1.5 BLUEHDI FEEL', 'MPV'),
('CITROEN', 'BERLINGO', '1.5 BLUEHDI SHINE', 'MPV'),
('CITROEN', 'SPACETOURER', '1.5 BLUEHDI FEEL', 'MPV'),
('CITROEN', 'SPACETOURER', '2.0 BLUEHDI SHINE', 'MPV'),
('CITROEN', 'E-C4', 'FEEL', 'C'),
('CITROEN', 'E-C4', 'SHINE', 'C');

-- CUPRA
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('CUPRA', 'BORN', '150 KW', 'C'),
('CUPRA', 'BORN', '170 KW E-BOOST', 'C'),
('CUPRA', 'FORMENTOR', '1.5 TSI', 'SUV'),
('CUPRA', 'FORMENTOR', '2.0 TSI 4DRIVE', 'SUV'),
('CUPRA', 'FORMENTOR', 'VZ 2.0 TSI', 'SUV'),
('CUPRA', 'FORMENTOR', 'VZ5', 'SUV'),
('CUPRA', 'LEON', '1.5 TSI', 'C'),
('CUPRA', 'LEON', '2.0 TSI', 'C'),
('CUPRA', 'LEON', 'VZ 2.0 TSI', 'C'),
('CUPRA', 'ATECA', '2.0 TSI 4DRIVE', 'SUV'),
('CUPRA', 'TAVASCAN', 'VZ', 'SUV');

-- DACIA
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('DACIA', 'SANDERO', '1.0 SCE ESSENTIAL', 'B'),
('DACIA', 'SANDERO', '1.0 TCE COMFORT', 'B'),
('DACIA', 'SANDERO', '1.0 TCE EXPRESSION', 'B'),
('DACIA', 'SANDERO', '1.0 TCE EXTREME', 'B'),
('DACIA', 'SANDERO STEPWAY', '1.0 TCE EXPRESSION', 'B'),
('DACIA', 'SANDERO STEPWAY', '1.0 TCE EXTREME', 'B'),
('DACIA', 'DUSTER', '1.0 TCE ECO-G ESSENTIAL', 'SUV'),
('DACIA', 'DUSTER', '1.0 TCE ECO-G EXPRESSION', 'SUV'),
('DACIA', 'DUSTER', '1.3 TCE EXPRESSION', 'SUV'),
('DACIA', 'DUSTER', '1.3 TCE EXTREME', 'SUV'),
('DACIA', 'DUSTER', '1.5 DCI EXPRESSION', 'SUV'),
('DACIA', 'DUSTER', '1.5 DCI EXTREME', 'SUV'),
('DACIA', 'JOGGER', '1.0 TCE ECO-G EXPRESSION', 'MPV'),
('DACIA', 'JOGGER', '1.0 TCE ECO-G EXTREME', 'MPV'),
('DACIA', 'JOGGER', '1.6 HYBRID EXPRESSION', 'MPV'),
('DACIA', 'JOGGER', '1.6 HYBRID EXTREME', 'MPV'),
('DACIA', 'SPRING', 'ESSENTIAL', 'A'),
('DACIA', 'SPRING', 'EXPRESSION', 'A'),
('DACIA', 'SPRING', 'EXTREME', 'A'),
('DACIA', 'LODGY', '1.5 DCI AMBIANCE', 'MPV'),
('DACIA', 'LODGY', '1.5 DCI LAUREATE', 'MPV'),
('DACIA', 'DOKKER', '1.5 DCI AMBIANCE', 'MPV'),
('DACIA', 'DOKKER', '1.5 DCI LAUREATE', 'MPV');

-- DFSK
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('DFSK', 'GLORY 580', '1.5T CVT COMFORT', 'SUV'),
('DFSK', 'GLORY 580', '1.5T CVT LUXURY', 'SUV'),
('DFSK', 'GLORY 560', '1.5 CVT COMFORT', 'SUV'),
('DFSK', 'GLORY 560', '1.5 CVT LUXURY', 'SUV'),
('DFSK', 'FENGON 500', '1.5T CVT', 'SUV'),
('DFSK', 'SERES 3', 'ELECTRIC', 'SUV');

-- DS
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('DS', 'DS 3 CROSSBACK', '1.2 PURETECH CHIC', 'B'),
('DS', 'DS 3 CROSSBACK', '1.2 PURETECH SO CHIC', 'B'),
('DS', 'DS 3 CROSSBACK', 'E-TENSE', 'B'),
('DS', 'DS 4', '1.2 PURETECH BASTILLE', 'C'),
('DS', 'DS 4', '1.6 PURETECH RIVOLI', 'C'),
('DS', 'DS 4', 'E-TENSE 225', 'C'),
('DS', 'DS 7', '1.6 PURETECH BASTILLE', 'SUV'),
('DS', 'DS 7', '1.6 PURETECH RIVOLI', 'SUV'),
('DS', 'DS 7', 'E-TENSE 4X4', 'SUV'),
('DS', 'DS 9', '1.6 PURETECH RIVOLI', 'E'),
('DS', 'DS 9', 'E-TENSE 250', 'E');

-- FERRARI
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('FERRARI', 'ROMA', 'V8', 'F'),
('FERRARI', 'ROMA SPIDER', 'V8', 'F'),
('FERRARI', 'PORTOFINO M', 'V8', 'F'),
('FERRARI', '296 GTB', 'V6 HYBRID', 'F'),
('FERRARI', '296 GTS', 'V6 HYBRID', 'F'),
('FERRARI', 'SF90', 'STRADALE', 'F'),
('FERRARI', 'SF90', 'SPIDER', 'F'),
('FERRARI', 'F8', 'TRIBUTO', 'F'),
('FERRARI', 'F8', 'SPIDER', 'F'),
('FERRARI', '812', 'SUPERFAST', 'F'),
('FERRARI', '812', 'GTS', 'F'),
('FERRARI', 'PUROSANGUE', 'V12', 'SUV');

-- FIAT
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('FIAT', '500', '1.0 HYBRID CULT', 'A'),
('FIAT', '500', '1.0 HYBRID DOLCEVITA', 'A'),
('FIAT', '500', '1.0 HYBRID SPORT', 'A'),
('FIAT', '500', 'E ACTION', 'A'),
('FIAT', '500', 'E PASSION', 'A'),
('FIAT', '500', 'E ICON', 'A'),
('FIAT', '500X', '1.3 T CULT', 'SUV'),
('FIAT', '500X', '1.3 T CROSS', 'SUV'),
('FIAT', '500X', '1.5 T HYBRID CROSS', 'SUV'),
('FIAT', '500X', '1.6 MJET CROSS', 'SUV'),
('FIAT', '500L', '1.4 T CROSS', 'MPV'),
('FIAT', '500L', '1.6 MJET CROSS', 'MPV'),
('FIAT', 'PANDA', '1.0 HYBRID CITY LIFE', 'A'),
('FIAT', 'PANDA', '1.0 HYBRID SPORT', 'A'),
('FIAT', 'PANDA', '1.2 CITY LIFE', 'A'),
('FIAT', 'PANDA', '0.9 TWINAIR CROSS 4X4', 'A'),
('FIAT', 'TIPO', '1.4 EASY', 'C'),
('FIAT', 'TIPO', '1.4 T LOUNGE', 'C'),
('FIAT', 'TIPO', '1.6 MJET LOUNGE', 'C'),
('FIAT', 'TIPO', '1.0 T CITY LIFE', 'C'),
('FIAT', 'TIPO CROSS', '1.0 T CROSS', 'C'),
('FIAT', 'TIPO CROSS', '1.5 HYBRID CROSS', 'C'),
('FIAT', 'EGEA', '1.4 EASY', 'C'),
('FIAT', 'EGEA', '1.4 T LOUNGE', 'C'),
('FIAT', 'EGEA', '1.6 MJET LOUNGE', 'C'),
('FIAT', 'EGEA CROSS', '1.4 T CROSS', 'C'),
('FIAT', 'EGEA CROSS', '1.5 HYBRID CROSS', 'C'),
('FIAT', 'EGEA HATCHBACK', '1.4 EASY', 'C'),
('FIAT', 'EGEA HATCHBACK', '1.4 T LOUNGE', 'C'),
('FIAT', 'EGEA STATION WAGON', '1.4 EASY', 'C'),
('FIAT', 'EGEA STATION WAGON', '1.6 MJET LOUNGE', 'C'),
('FIAT', 'DOBLO', '1.6 MJET PREMIO', 'MPV'),
('FIAT', 'DOBLO', '1.6 MJET SAFELINE', 'MPV'),
('FIAT', 'DOBLO CARGO', '1.3 MJET', 'TİCARİ'),
('FIAT', 'DOBLO CARGO', '1.6 MJET MAXI', 'TİCARİ'),
('FIAT', 'FIORINO', '1.3 MJET COMBI', 'TİCARİ'),
('FIAT', 'FIORINO', '1.3 MJET CARGO', 'TİCARİ'),
('FIAT', 'DUCATO', '2.3 MJET', 'TİCARİ'),
('FIAT', 'DUCATO', '2.3 MJET MAXI', 'TİCARİ'),
('FIAT', 'TALENTO', '1.6 MJET', 'TİCARİ'),
('FIAT', 'TALENTO', '2.0 MJET', 'TİCARİ'),
('FIAT', 'SCUDO', '1.5 BLUEHDI', 'TİCARİ'),
('FIAT', 'SCUDO', '2.0 BLUEHDI', 'TİCARİ'),
('FIAT', 'FULLBACK', '2.4 D CROSS', 'PICKUP'),
('FIAT', 'FULLBACK', '2.4 D ADVENTURE', 'PICKUP');

-- FORD
INSERT INTO arac_veritabani (marka, model, paket, segment) VALUES
('FORD', 'FIESTA', '1.0 ECOBOOST TREND', 'B'),
('FORD', 'FIESTA', '1.0 ECOBOOST TITANIUM', 'B'),
('FORD', 'FIESTA', '1.0 ECOBOOST ST-LINE', 'B'),
('FORD', 'FIESTA', '1.5 TDCI TITANIUM', 'B'),
('FORD', 'FIESTA', 'ST 1.5 ECOBOOST', 'B'),
('FORD', 'FOCUS', '1.0 ECOBOOST TREND', 'C'),
('FORD', 'FOCUS', '1.0 ECOBOOST TITANIUM', 'C'),
('FORD', 'FOCUS', '1.5 ECOBOOST ST-LINE', 'C'),
('FORD', 'FOCUS', '1.5 ECOBLUE TITANIUM', 'C'),
('FORD', 'FOCUS', '1.5 ECOBLUE ST-LINE X', 'C'),
('FORD', 'FOCUS', '2.3 ECOBOOST ST', 'C'),
('FORD', 'FOCUS ACTIVE', '1.0 ECOBOOST', 'C'),
('FORD', 'FOCUS ACTIVE', '1.5 ECOBLUE', 'C'),
('FORD', 'PUMA', '1.0 ECOBOOST TITANIUM', 'SUV'),
('FORD', 'PUMA', '1.0 ECOBOOST ST-LINE', 'SUV'),
('FORD', 'PUMA', '1.0 ECOBOOST ST-LINE X', 'SUV'),
('FORD', 'PUMA', '1.5 ECOBLUE ST-LINE', 'SUV'),
('FORD', 'PUMA', '1.0 ECOBOOST ST', 'SUV'),
('FORD', 'KUGA', '1.5 ECOBOOST TITANIUM', 'SUV'),
('FORD', 'KUGA', '1.5 ECOBOOST ST-LINE', 'SUV'),
('FORD', 'KUGA', '1.5 ECOBLUE TITANIUM', 'SUV'),
('FORD', 'KUGA', '2.0 ECOBLUE ST-LINE X', 'SUV'),
('FORD', 'KUGA', '2.5 PHEV ST-LINE', 'SUV'),
('FORD', 'KUGA', '1.5 ECOBOOST VIGNALE', 'SUV'),
('FORD', 'TOURNEO COURIER', '1.0 ECOBOOST TITANIUM', 'MPV'),
('FORD', 'TOURNEO COURIER', '1.5 TDCI TITANIUM', 'MPV'),
('FORD', 'TOURNEO CONNECT', '1.5 ECOBOOST TITANIUM', 'MPV'),
('FORD', 'TOURNEO CONNECT', '1.5 ECOBLUE TITANIUM', 'MPV'),
('FORD', 'TOURNEO CUSTOM', '2.0 ECOBLUE TITANIUM', 'MPV'),
('FORD', 'TOURNEO CUSTOM', '2.0 ECOBLUE TITANIUM X', 'MPV'),
('FORD', 'TRANSIT COURIER', '1.5 TDCI', 'TİCARİ'),
('FORD', 'TRANSIT CONNECT', '1.5 ECOBLUE', 'TİCARİ'),
('FORD', 'TRANSIT CUSTOM', '2.0 ECOBLUE', 'TİCARİ'),
('FORD', 'TRANSIT', '2.0 ECOBLUE', 'TİCARİ'),
('FORD', 'RANGER', '2.0 ECOBLUE XL', 'PICKUP'),
('FORD', 'RANGER', '2.0 ECOBLUE XLT', 'PICKUP'),
('FORD', 'RANGER', '2.0 ECOBLUE WILDTRAK', 'PICKUP'),
('FORD', 'RANGER', '3.0 V6 WILDTRAK', 'PICKUP'),
('FORD', 'RANGER RAPTOR', '3.0 V6 ECOBOOST', 'PICKUP'),
('FORD', 'MUSTANG', '2.3 ECOBOOST', 'D'),
('FORD', 'MUSTANG', '5.0 V8 GT', 'D'),
('FORD', 'MUSTANG MACH-E', 'STANDARD RANGE', 'SUV'),
('FORD', 'MUSTANG MACH-E', 'EXTENDED RANGE', 'SUV'),
('FORD', 'MUSTANG MACH-E', 'GT', 'SUV'),
('FORD', 'EXPLORER', '3.0 V6 PHEV ST-LINE', 'SUV'),
('FORD', 'EXPLORER', '3.0 V6 PHEV PLATINUM', 'SUV'),
('FORD', 'BRONCO', '2.7 V6', 'SUV'),
('FORD', 'F-150', '3.5 V6 ECOBOOST', 'PICKUP'),
('FORD', 'F-150', '5.0 V8', 'PICKUP'),
('FORD', 'F-150', 'RAPTOR', 'PICKUP');
